version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      
  fastapi:
    build:
      context: .
    container_name: fastapi
    ports:
      - "2188:2188"
    depends_on:
      - redis

