FROM ubuntu:22.04

# 비대화형 설치 환경 설정
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Seoul

RUN apt update && apt install -y curl gnupg

# ollama 수동 설치. 공식 패키지는 os 예전 , py3.10 버전이라... langgraph 사용 불가
# Download and install Ollama
RUN curl -L https://ollama.com/download/ollama-linux-amd64.tgz -o ollama-linux-amd64.tgz \
&& tar -xzf ollama-linux-amd64.tgz && cp ./bin/ollama /usr/local/bin/ && chmod +x /usr/local/bin/ollama


# Python 3.12 설치 위한 PPA 등록
RUN apt-get update && apt-get install -y \
    software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    apt-get update && apt-get install -y \
    python3.12 \
    python3.12-dev \
    python3.12-venv \
    python3-pip \
    python3-setuptools \
    wget \
    build-essential \
    ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# 기본 Python 버전으로 3.12 설정
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1

RUN python3 --version  # 확인

# 캐시 정리로 이미지 크기 줄이기
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# base image 만들기
# 빌드 명령어: docker build -t bc_backend:1.0 -f Dockerfile.base .