FROM ubuntu:22.04

# 비대화형 설치 환경 설정
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Seoul

# ollama 설치
RUN apt update && apt install -y curl gnupg \
 && curl -fsSL https://ollama.com/download/ollama-install.sh | sh

# Python 3.12 설치
RUN apt update && apt install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    apt update && apt install -y python3.12 python3.12-venv python3.12-dev python3-pip && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1

RUN python3 --version  # 확인

# 캐시 정리로 이미지 크기 줄이기
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# base image 만들기
# 빌드 명령어: docker build -t bc_backend:1.0 -f Dockerfile.base .